### PR TITLE
Authenticators cleanup

### PR DESCRIPTION
**Pull request by robertjd**
- Renamed api_auth.md to authenticators.md
- Added new `StormpathAssertionAuthenticator`
- Minor cleanup of description and header depth of other authenticators

Ping @lhazlewood and @omgitstom RE the `StormpathAssertionAuthenticator` specifically the `getAccessTokenResponse` method on the authentication result.  Do you feel this is appropriately named?

### CODE REVIEW

**Comment by omgitstom** [comment]
getAccessTokenResponse will return a Oauth2AuthenticationResult?

To be a little clearer about my question,  getAccessTokenResponse I think mights a lot of sense from the developer POV, but what do they get back?

An AccessTokenResult or  Oauth2AuthenticationResult or an AccessToken?  I think it has to be a result object, because it could error ect...

**Comment by robertjd** [comment]
Yes, I think `Oauth2AuthenticationResult` would be a good way to encapsulate the response from our `:appId/oauth/token` endpoint.  In that case, I think the method should be `authenticationResult.getOauth2AuthenticationResult()`

**Comment by robertjd** [comment]
We need to resolve this issue, as we're ready to move forward with the Node SDK implementation.  My current interpretation and suggestion is the following:
- The `StormpathAssertionAuthenticator` should take a Stormpath Token (the `jwtResult` from an ID Site or SAML Callback) and after verifying the JWT (signature, expiration) it should return a `StormpathAssertionAuthenticationResult`
- The `StormpathAssertionAuthenticationResult` should provide a `getOauth2AuthenticationResult()` method, which will POST the Stormpath Token to the application's `/oauth/token` endpoint as `grant_type=stormpath_token`.  This method should return a `Oauth2AuthenticationResult`.
- The `Oauth2AuthenticationResult` should have a method `getAccessTokenResponse()`, which will return a JSON object that is [Access Token Response per RFC 6749](https://tools.ietf.org/html/rfc6749#section-4.1.4).
- Both authentication result types, `Oauth2AuthenticationResult` and `StormpathAssertionAuthenticationResult`, should have a `getAccount()` method for fetching the account that is associated with the result.

Ping @lhazlewood and @omgitstom for review of this proposal.  I'll modify the PR after review/discussion/etc.

**Comment by robertjd** [comment]
I've updated this PR with our changes from today's meeting.  The changes nullify my previous comment, and are thus:
- The `StormpathAssertionAuthenticator` verifies JWTs from ID Site or SAML callbacks and returns a `StormpathAssertionAuthenticationResult`
- The `OAuthStormpathTokenAuthenticator` exchanges a ID Site or SAML callback JWT  for an `OAuthAccessTokenResult`, obtained from the application's `/oauth/token` endpoint.

We also realized that this SDK spec was defining these authenticators as request authenticators, which is not correct.  The framework spec should be defining the request authenticators. This SDK spec defines the raw authenticator interface, with the required authentication parameters and result types.  I've updated accordingly.

**Pull request merged**
